# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_sample_lscnn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='training_sample_lscnn.proto',
  package='',
  serialized_pb=_b('\n\x1btraining_sample_lscnn.proto\"\x8f\x04\n\x15training_sample_lscnn\x12\n\n\x02xp\x18\x01 \x01(\x0c\x12\x10\n\x08xp_shape\x18\x02 \x03(\x05\x12\x0b\n\x03Vxp\x18\x03 \x01(\x0c\x12\x11\n\tVxp_shape\x18\x04 \x03(\x05\x12\x0b\n\x03\x41xp\x18\x05 \x01(\x0c\x12\x11\n\tAxp_shape\x18\x06 \x03(\x05\x12\x0b\n\x03Lxp\x18\x07 \x01(\x0c\x12\x11\n\tLxp_shape\x18\x08 \x03(\x05\x12\n\n\x02xn\x18\t \x01(\x0c\x12\x10\n\x08xn_shape\x18\n \x03(\x05\x12\x0b\n\x03Vxn\x18\x0b \x01(\x0c\x12\x11\n\tVxn_shape\x18\x0c \x03(\x05\x12\x0b\n\x03\x41xn\x18\r \x01(\x0c\x12\x11\n\tAxn_shape\x18\x0e \x03(\x05\x12\x0b\n\x03Lxn\x18\x0f \x01(\x0c\x12\x11\n\tLxn_shape\x18\x10 \x03(\x05\x12\n\n\x02yp\x18\x11 \x01(\x0c\x12\x10\n\x08yp_shape\x18\x12 \x03(\x05\x12\x0b\n\x03Vyp\x18\x13 \x01(\x0c\x12\x11\n\tVyp_shape\x18\x14 \x03(\x05\x12\x0b\n\x03\x41yp\x18\x15 \x01(\x0c\x12\x11\n\tAyp_shape\x18\x16 \x03(\x05\x12\x0b\n\x03Lyp\x18\x17 \x01(\x0c\x12\x11\n\tLyp_shape\x18\x18 \x03(\x05\x12\n\n\x02yn\x18\x19 \x01(\x0c\x12\x10\n\x08yn_shape\x18\x1a \x03(\x05\x12\x0b\n\x03Vyn\x18\x1b \x01(\x0c\x12\x11\n\tVyn_shape\x18\x1c \x03(\x05\x12\x0b\n\x03\x41yn\x18\x1d \x01(\x0c\x12\x11\n\tAyn_shape\x18\x1e \x03(\x05\x12\x0b\n\x03Lyn\x18\x1f \x01(\x0c\x12\x11\n\tLyn_shape\x18  \x03(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAINING_SAMPLE_LSCNN = _descriptor.Descriptor(
  name='training_sample_lscnn',
  full_name='training_sample_lscnn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xp', full_name='training_sample_lscnn.xp', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xp_shape', full_name='training_sample_lscnn.xp_shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vxp', full_name='training_sample_lscnn.Vxp', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vxp_shape', full_name='training_sample_lscnn.Vxp_shape', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Axp', full_name='training_sample_lscnn.Axp', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Axp_shape', full_name='training_sample_lscnn.Axp_shape', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lxp', full_name='training_sample_lscnn.Lxp', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lxp_shape', full_name='training_sample_lscnn.Lxp_shape', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xn', full_name='training_sample_lscnn.xn', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xn_shape', full_name='training_sample_lscnn.xn_shape', index=9,
      number=10, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vxn', full_name='training_sample_lscnn.Vxn', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vxn_shape', full_name='training_sample_lscnn.Vxn_shape', index=11,
      number=12, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Axn', full_name='training_sample_lscnn.Axn', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Axn_shape', full_name='training_sample_lscnn.Axn_shape', index=13,
      number=14, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lxn', full_name='training_sample_lscnn.Lxn', index=14,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lxn_shape', full_name='training_sample_lscnn.Lxn_shape', index=15,
      number=16, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yp', full_name='training_sample_lscnn.yp', index=16,
      number=17, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yp_shape', full_name='training_sample_lscnn.yp_shape', index=17,
      number=18, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vyp', full_name='training_sample_lscnn.Vyp', index=18,
      number=19, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vyp_shape', full_name='training_sample_lscnn.Vyp_shape', index=19,
      number=20, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ayp', full_name='training_sample_lscnn.Ayp', index=20,
      number=21, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ayp_shape', full_name='training_sample_lscnn.Ayp_shape', index=21,
      number=22, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lyp', full_name='training_sample_lscnn.Lyp', index=22,
      number=23, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lyp_shape', full_name='training_sample_lscnn.Lyp_shape', index=23,
      number=24, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yn', full_name='training_sample_lscnn.yn', index=24,
      number=25, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yn_shape', full_name='training_sample_lscnn.yn_shape', index=25,
      number=26, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vyn', full_name='training_sample_lscnn.Vyn', index=26,
      number=27, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vyn_shape', full_name='training_sample_lscnn.Vyn_shape', index=27,
      number=28, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ayn', full_name='training_sample_lscnn.Ayn', index=28,
      number=29, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ayn_shape', full_name='training_sample_lscnn.Ayn_shape', index=29,
      number=30, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lyn', full_name='training_sample_lscnn.Lyn', index=30,
      number=31, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lyn_shape', full_name='training_sample_lscnn.Lyn_shape', index=31,
      number=32, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=559,
)

DESCRIPTOR.message_types_by_name['training_sample_lscnn'] = _TRAINING_SAMPLE_LSCNN

training_sample_lscnn = _reflection.GeneratedProtocolMessageType('training_sample_lscnn', (_message.Message,), dict(
  DESCRIPTOR = _TRAINING_SAMPLE_LSCNN,
  __module__ = 'training_sample_lscnn_pb2'
  # @@protoc_insertion_point(class_scope:training_sample_lscnn)
  ))
_sym_db.RegisterMessage(training_sample_lscnn)


# @@protoc_insertion_point(module_scope)
